### ISSUE TITLE
\Ray\MediaQuery\MediaQueryLogger causing problems with Uuids

### ISSUE THREAD

**Issue by toby-griffiths** [ray-di/Ray.MediaQuery#57] opened 2024-04-24 12:57 UTC
I've juststarted playing with BEAR.Sunday, so please excude my lack of knowledge & possibly understanding.

### Bug Report

I am using (binary) Uuids for Ids in my new app, and whilst I have this working OK for saving the values to the d/b, an error is being throw because the `MediaQueryLogger` cannot json_encode the binary string.

I thought I could use AOP to intercept the Uuid values being passed to logger, however there are 2 problems with this…

1. The values being passed are the converted ones, not the original ones, so they'll need 'unconverting' (which I'm doing in a decorator of the `MediaQueryLogger`);
2. The `MediaQueryLogger` class is final, so it's not possible to intercept the `log()` method call.

### How to reproduce

1. Create the following files & classes…

    ```sql
    # asset_create.sql
    INSERT INTO assets (id, name, createdAt, updatedAt)
    VALUES (:id, :name, :createdAt, :updatedAt);
    ```
    
    ```php
    <?php
    // src/Resource/App/Assets.php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Resource\App;
    
    use BEAR\Package\Annotation\ReturnCreatedResource;
    use BEAR\Resource\ResourceObject;
    use DateTimeInterface;
    use Koriym\HttpConstants\ResponseHeader;
    use Koriym\HttpConstants\StatusCode;
    use TobyGriffiths\NetWorth\Query\AssetCommandInterface;
    use TobyGriffiths\NetWorth\Uuid\UuidFactory;
    
    use function uri_template;
    
    class Assets extends ResourceObject
    {
        public function __construct(
            private UuidFactory $uuidFactory,
            private readonly AssetCommandInterface $command,
            private readonly DateTimeInterface $now,
        ) {
        }
    
        public function onPost(string $name): static
        {
            $id = $this->uuidFactory->uuid7($this->now);
            $this->command->create($id, $name);
    
            $this->code = StatusCode::CREATED;
            $this->headers[ResponseHeader::LOCATION] = uri_template('/assets{?id}', ['id' => $id->toString()]);
    
            return $this;
        }
    }
    ```
    
    ```php
    <?php
    // src/Uuid/UuidFactory.php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Uuid;
    
    use DateTimeImmutable;
    use Ramsey\Uuid\UuidFactory as RamseyUuidFactory;
    
    final readonly class UuidFactory implements UuidFactoryInterface
    {
        public function __construct(
            private RamseyUuidFactory $innerFactory,
        ) {
        }
    
        public function uuid7(DateTimeImmutable|null $dateTime = null): Uuid
        {
            return new Uuid($this->innerFactory->uuid7($dateTime));
        }
    }
    ```
    
    ```php
    // src/Uuid/Uuid.php
    <?php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Uuid;
    
    use Ramsey\Uuid\UuidInterface as RamseyUuidInterface;
    
    final readonly class Uuid
    {
        public function __construct(
            private RamseyUuidInterface $innerUuid,
        ) {
        }
    
        public function toString(): string
        {
            return $this->innerUuid->toString();
        }
    
        public function toScalar(): string
        {
            return $this->innerUuid->getBytes();
        }
    }
    ```

2. Bind the necessary services…

    ```php
    <?php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Module;
    
    use BEAR\Dotenv\Dotenv;
    use BEAR\Package\AbstractAppModule;
    use BEAR\Package\PackageModule;
    use BEAR\Resource\Module\JsonSchemaModule;
    use Ramsey\Uuid\UuidFactory as RamseyUuidFactory;
    use Ramsey\Uuid\UuidFactoryInterface as RamseyUuidFactoryInterface;
    use Ray\AuraSqlModule\AuraSqlModule;
    use Ray\Di\ProviderInterface;
    use Ray\Di\Scope;
    use Ray\IdentityValueModule\IdentityValueModule;
    use Ray\MediaQuery\DbQueryConfig;
    use Ray\MediaQuery\MediaQueryLogger;
    use Ray\MediaQuery\MediaQueryLoggerInterface;
    use Ray\MediaQuery\MediaQueryModule;
    use Ray\MediaQuery\Queries;
    use TobyGriffiths\NetWorth\MediaQuery\BinaryDataMediaQueryLoggerDecorator;
    use TobyGriffiths\NetWorth\Uuid\UuidFactory;
    use TobyGriffiths\NetWorth\Uuid\UuidFactoryInterface;
    
    use function dirname;
    use function getenv;
    
    class AppModule extends AbstractAppModule
    {
        protected function configure(): void
        {
            (new Dotenv())->load(dirname(__DIR__, 2));
    
            $this->overrideMediaQueryLogger();
    
            $this->installDbModules();
    
            $this->bind(UuidFactoryInterface::class)->to(UuidFactory::class)->in(Scope::SINGLETON);
            $this->bind(RamseyUuidFactoryInterface::class)->to(RamseyUuidFactory::class)->in(Scope::SINGLETON);
    
            $this->install(new PackageModule());
        }
    
        private function installDbModules(): void
        {
            $this->install(
                new AuraSqlModule(
                    (string) getenv('DB_DSN'),
                    (string) getenv('DB_USER'),
                    (string) getenv('DB_PW'),
                    (string) getenv('DB_SLAVE'),
                ),
            );
    
            $this->install(
                new MediaQueryModule(
                    Queries::fromDir($this->appMeta->appDir . '/src/Query'),
                    [
                        new DbQueryConfig($this->appMeta->appDir . '/var/sql'),
                    ],
                ),
            );
    
            $this->install(new IdentityValueModule());
    
            $this->install(
                new JsonSchemaModule(
                    $this->appMeta->appDir . '/var/schema/response',
                    $this->appMeta->appDir . '/var/schema/request',
                ),
            );
        }
    
        private function overrideMediaQueryLogger(): void
        {
        // Commenting this fix out to demo the problem
        //
        //    $this
        //        ->bind(MediaQueryLoggerInterface::class)
        //        ->to(BinaryDataMediaQueryLoggerDecorator::class)
        //        ->in(Scope::SINGLETON);
        //    $this->bind(MediaQueryLogger::class);
        }
    }
    ```

3. Call the endpoint…

```shell
$ php ./bin/app/php post '/assets?name=wibble'
```

You can see I've commented out a call to `overrideMediaQueryLogger()`, which binds the following class to fix the issue, for now…

```php
<?php

declare(strict_types=1);

namespace TobyGriffiths\NetWorth\MediaQuery;

use InvalidArgumentException;
use Ramsey\Uuid\UuidFactory;
use Ray\MediaQuery\MediaQueryLogger as RayMediaQueryLogger;
use Ray\MediaQuery\MediaQueryLoggerInterface;

use function mb_check_encoding;

/**
 * Drop in replacement of Ray\MediaQuery\MediaQueryLogger that can handle binary Uuid values.
 */
final class BinaryDataMediaQueryLoggerDecorator implements MediaQueryLoggerInterface
{
    public function __construct(
        private readonly RayMediaQueryLogger $decorated,
        // We use the concrete class here because that has needed to be bound
        private readonly UuidFactory $uuidFactory,
    ) {
    }

    public function start(): void
    {
        $this->decorated->start();
    }

    /**
     * {@inheritDoc}
     */
    public function log(string $queryId, array $values): void
    {
        foreach ($values as &$value) {
            if (mb_check_encoding($value, 'UTF-8')) {
                continue;
            }

            // Replace this with injected handlers for different types of binary data?
            try {
                $value = $this->uuidFactory
                    ->fromBytes($value)
                    ->toString();
            } catch (InvalidArgumentException) {
                // Don't convert the value, we'll just fail for now.
            }
        }
    }

    public function __toString(): string
    {
        return $this->decorated->__toString();
    }
}
```

So I have a proposed solution, which I'm happy to PR…

1. Remove the `final` from `MediaQueryLogger`;
2. Include the original values in the call to `MediaQueryLoggerInterface::log()`, optional, so as not to break anyone's
   overrides…

    ```php
    public function log(string $queryId, array $values, array $originalValues = []): void;
    ```

I also found it difficult to work out how to decorate the original `MediaQueryLogger` instance, which is straight pretty
forward in Symfony, so if anyone can enlighten me on that, I can improve my workaround until this has a better fix?

If I can provide any more context info, or test some things, please let me know.

**Comment by koriym** [comment] 2024-04-25 13:33
Thanks for the feedback!

My solution in this case is not by AOP but by DI. (I will explain later why not AOP out)

There are two ways to do this with DI.
One way is to not use the implementation that is currently bound and the other way is to use it.

Method A: (not use)

The current `MediaQueryLogger` implementation is very simple and was actually based on the premise of changing the messages and log content according to the user's requirements.

https://github.com/ray-di/Ray.MediaQuery/blob/1.x/src/MediaQueryLogger.php#L30

So you can have it replaced entirely by the logger class you created. I recommend this.

```php
$this->bind(MediaQueryLoggerInterface::class)->to(YourLoggerInterface::class)->in(Scope::SINGLETON);
```

Method B: Another pattern is to use the current implementation and decorate it by composition. (I don't think this is necessary in this case, but I would like to share this method for a different case.)

You take the original dependency with a `delegate` qualifier and use it.

```php
final class YourLogger implements MediaQueryLoggerInterface.
{
    public function __construct().
        #[Named('delegate')] private readonly MediaQueryLoggerInterface $logger
    ) {}

public function start(): void
    {
        // delegate to the original logger
        $this->logger->start();
    }

    public function log(string $queryId, array $values): void
    {
        $decorate = function ($values) {
            // your logic here
            return $values;.
        };
        $modifiedValues = $decorate($values);
        // delegate to the original logger
        $this->logger->log($queryId, $modifiedValues);
    }

    public function __toString(): string
    {
        return $this->logger->__toString();
    }
}
```

This requires two bindings.

```php
$this->bind(MediaQueryLoggerInterface::class)->to(YourLogger::class)->in(Scope::SINGLETON);
$this->bind(MediaQueryLoggerInterface::class)->annotateWith('delegate')->to( MediaQueryLogger::class)->in(Scope::SINGLETON);
```

I was able to use the composition pattern to decorate.

Then I will also explain why I do not recommend using AOP here.

Because what your interceptor is trying to do is more of a decorating and patching of the original code than a transversal interest. They are deeply coupled. Also, the interceptor is only used for that method, not across the board.

So I don't think it fits in with AOP, which separates transversal interests.

What do you think?

**Comment by NaokiTsuchiya** [comment] 2024-04-25 18:05
@toby-griffiths 

Thanks for the detailed reproduction.

In confirming the actual operation, could you please share the following as well?

* table schema of assets
* code of `TobyGriffiths\NetWorth\Query\AssetCommandInterface`

---

As koriym has already written, it can be extended by binding any implementation class to MediaQueryLoggerInterface.

**Comment by NaokiTsuchiya** [comment] 2024-04-26 03:21
> 2. Include the original values in the call to `MediaQueryLoggerInterface::log()`, optional, so as not to break anyone's
>    overrides…
>    ```
>    public function log(string $queryId, array $values, array $originalValues = []): void;
>    ```

This suggestion may be necessary to extend the logger.

If this extension is added, I think the logger needs to be able to handle VOs in a unified manner like ParamConverter.

In this example alone, it seems that Uuid should implement __toString, but since ParamConverter prefers __toString to toScaler, ParamConverter's processing may need to be adjusted as well.

**Comment by toby-griffiths** [comment] 2024-04-27 10:16
@koriym thanks for the extensive explanation. It’s very helpful, especially to a new starter.

I had really wanted to use the decorator pattern, but couldn’t work out how to do that from the DI docs. I thought the Named attribute needed to be added where it was used, rather than, in your example, where it is used.

> Method B: Another pattern is to use the current implementation and decorate it by composition. (I don't think this is necessary in this case, but I would like to share this method for a different case.)
> 
> You take the original dependency with a `delegate` qualifier and use it.
> 
> ```
> final class YourLogger implements MediaQueryLoggerInterface.
> {
>     public function __construct().
>         #[Named('delegate')] private readonly MediaQueryLoggerInterface $logger
>     ) {}
> 
> public function start(): void
>     {
>         // delegate to the original logger
>         $this->logger->start();
>     }
> 
>     public function log(string $queryId, array $values): void
>     {
>         $decorate = function ($values) {
>             // your logic here
>             return $values;.
>         };
>         $modifiedValues = $decorate($values);
>         // delegate to the original logger
>         $this->logger->log($queryId, $modifiedValues);
>     }
> 
>     public function __toString(): string
>     {
>         return $this->logger->__toString();
>     }
> }
> ```
> 
> This requires two bindings.
> 
> ```
> $this->bind(MediaQueryLoggerInterface::class)->to(YourLogger::class)->in(Scope::SINGLETON);
> $this->bind(MediaQueryLoggerInterface::class)->annotateWith('delegate')->to( MediaQueryLogger::class)->in(Scope::SINGLETON);
> ```

In your example I see you use ‘delegate’. Is this an arbitrary name, or does this have special meaning?

Also, if I wanted to use the decorator pattern to decorate the same instance multiple times, is there a way to do this in a specific, predictable order?

**Comment by toby-griffiths** [comment] 2024-04-27 10:31
> This suggestion may be necessary to extend the logger.
> 
> If this extension is added, I think the logger needs to be able to handle VOs in a unified manner like ParamConverter.
> 
> In this example alone, it seems that Uuid should implement __toString, but since ParamConverter prefers __toString to toScaler, ParamConverter's processing may need to be adjusted as well.

That’s a good point. This would be a breaking change to change the priority order.

If we we just passed the original values to the logger and used the ParamConverter inside it then that could be a non-breaking change, and allow overriding with more options. Would that be acceptable? I can PR that? What’s the best way to go about this? Which branch should it target 🎯?

So to be clear, the plan would be to pass the original values to the default logger, and use ParamConverter inside the logger.

And, perhaps the option of another PR to add an alternative ParamConverter with the priority of asScalar()/__toString() reversed?

**Comment by koriym** [comment] 2024-04-27 12:19
@toby-griffiths Arbitrary, I used "original" or "default" before. Repeating such an inject would make it a decorator. (I myself would avoid such strong joins if possible. But I suppose there are cases where it would be valid.)

**Comment by koriym** [comment] 2024-04-28 01:46
> This would be a breaking change to change the priority order.

This is possible because we do not yet have a stable release. We can also offer existing users a way to leave the current converter as it is and bind against it.

Interesting thought by @NaokiTsuchiya. Shall we consider something along these lines?

**Comment by koriym** [comment] 2024-04-28 01:49
Even in this case, it would be better to inject a dependency that ParamConverter "preferentially converts" and use it, rather than "changing the order".

**Comment by koriym** [comment] 2024-04-29 15:32
To avoid overkill, we would like to focus on this first: there are two points.

1. change the Logger interface. (BC break)

```
public function log(string $queryId, array $bindValues, array $originalValues): void;.
```

The user is now free to control what is logged in the logger.

2. the MediaQueryLogger only deals with binary cases.

MediaQueryLogger is merely an example, and it should be the application's job to decide what and how to log. But the current state of the error should be fixed. How about something like this, which is a coping mechanism?


```php
foreach ($values as &$value) {
    if (! mb_check_encoding($value, 'UTF-8')) {
        $value = base64_encode($value); // or '(binary) ' . base64_encode($value); // or '(binary) ' .
    }
}
````

MediaQueryLogger is only minimally functional and does not use dependencies.

We'll talk more about this, like injecting PriorityConverter into ParamConverter, or changing the order of toScalar/toString, next.

What do you think?

---

考えをまとめました。オーバーキルにならないように、まずはこの点に絞りたいと思います。２点あります。

1. Loggerのインターフェイスを変更します。(BC break)

```
public function log(string $queryId, array $bindValues, array $originalValues): void;
```

これで、ユーザーは自由にロガーに記録する内容をコントロールできるようになります。

2. MediaQueryLoggerではバイナリの時だけの対処を行う。

MediaQueryLoggerは単に一例に過ぎず、何をどう記録するかはアプリケーションの仕事であるべきです。ですが、今のエラーの状態は直すべきです。このような対処的なものでどうでしょうか？


```php
foreach ($values as &$value) {
    if (! mb_check_encoding($value, 'UTF-8')) {
        $value = base64_encode($value); // or '(binary) ' . base64_encode($value);
    }
}
```

MediaQueryLoggerはあくまで最低限の機能に留め、依存を使ったりしません。
これ以上の話、ParamConverterにPriorityConverterをインジェクトするとか、toScalar/toStringの順番を変えるとかは次の話にします。

どうでしょか？

**Closed as completed** 2024-05-11 12:59 UTC
